### ISSUE TITLE
Error loading the model when testing the docker file

### ISSUE THREAD

**Issue by MattiooFR** [philschmid/serverless-bert-huggingface-aws-lambda-docker#1]
I created a slightly different version of your model, using T5 for doing text summarization, but I don't know why it doesn't find the model files. It looks for "./model' as a model in the huggingface library. I checked in the docker machine how was done the file architecture by doing ```ls``` and there I see my files but everything is flat, there is no ./model folder. So I tried using only "." as a path but then it says **Error no file named [‘pytorch_model.bin’, ‘tf_model.h5’] found**.

Any idea ?

My code is [here](https://github.com/MattiooFR/aws-lambda-t5-summarizer)

**Comment by philschmid** [comment]
Hi, 

i am going to look into code and hopefully, find out whats wrong

**Comment by philschmid** [comment]
Found it. the correct command in the `dockerfile` to `COPY` the files should be `./` and not `./*`. I cloned your repository and not getting the error (model not found) anymore, but there are other errors in your code. 

```dockerfile
# Copy function code and models into our /var/task
COPY ./ ${LAMBDA_TASK_ROOT}/
```

and btw. why are you installing Pytorch and Tensorflow?

**Comment by MattiooFR** [comment]
Thanks for your quick reply ! I installed it because an error was telling me that ```TFAutoModelWithLMHead``` needs it.
Now I'm using T5Tokenizer, T5ForConditionalGeneration and I don't need it anymore !
I fixed my errors and now it seems to work, hurray !
